call foreign function
tetratelabs/proxy-wasm-go-sdk pull request #163
Opened 2021-05-18 13:53 UTC by zhenjunMa

recently,  i want to call the host function in my wasm,  i found there is a spec define this interface `proxy_call_foreign_function `

more info: https://github.com/proxy-wasm/spec/tree/master/abi-versions/vNEXT#foreign-function-interface-ffi

my wasm is written by golang, so i use this repo in my project, but it doesn't implement `proxy_call_foreign_function `, so i do this.

2021-05-18 13:57 UTC, zhenjunMa commented
this one  #163

2021-05-19 01:34 UTC, mathetake commented on proxywasm/hostcall.go
> +func DispatchForeignFuncCall(funcName string, param string) (ret string, err error) {
this is not async function but synchronous and nor a callout, so `Dispatch` is not an appropriate name.

And I definitely don't think you should expose the mangling scheme of `param` to users. Could you please add an example under `examples` directory and demonstrate how this is used?

2021-05-19 01:36 UTC, mathetake requested changes

2021-05-19 01:36 UTC, mathetake commented on proxywasm/hostcall.go
> +func DispatchForeignFuncCall(funcName string, param string) (ret string, err error) {
```suggestion
func CallForeignFunction(funcName string, param string) (ret string, err error) {
```

2021-05-19 01:36 UTC, mathetake commented on proxywasm/rawhostcall/rawhostcall.go
> +
could you add this to `rawhostcall_mock.go` as well so we can test this locally?

2021-05-19 08:53 UTC, mathetake requested changes
Sorry, I was kind of confused so please ignore that comment (`And I definitely don't think you should expose the mangling scheme of param to users.`).

You can use "compress" function in Envoy https://github.com/envoyproxy/envoy/blob/main/source/extensions/common/wasm/foreign.cc#L30 to pass e2e test.

2021-05-19 08:53 UTC, mathetake commented on e2e/e2e_test.go
> +
unnecessary change.

2021-05-19 08:53 UTC, mathetake commented on e2e/e2e_test.go
> +
remove the empty line to line with the style.

2021-05-19 08:53 UTC, mathetake commented on e2e/e2e_test.go
> +
ditto.

2021-05-19 08:53 UTC, mathetake commented on e2e/e2e_test.go
> +		admin:       28311,
use the different ports so we can avoid the port collision.

2021-05-19 08:53 UTC, mathetake commented on proxywasm/hostcall.go
> +func CallForeignFunction(funcName string, param string) (ret string, err error) {
let's have []byte as a type for param which is more generic 
```suggestion
func CallForeignFunction(funcName string, param []byte) (ret string, err error) {
```

2021-05-19 08:53 UTC, mathetake commented on proxytest/root.go
> +var funcMap = map[string]func(string)string {
```suggestion
var foreignFunctions = map[string]func([]byte)[]byte {
```

2021-05-19 08:58 UTC, mathetake commented on proxywasm/hostcall.go
> +func CallForeignFunction(funcName string, param string) (ret string, err error) {
and also have the return to be []byte as well
```suggestion
func CallForeignFunction(funcName string, param string) (ret []byte, err error) {
```

2021-05-19 11:29 UTC, mathetake reviewed
Thanks, almost there.

2021-05-19 11:29 UTC, mathetake commented on e2e/e2e_test.go
> -
thanks!

2021-05-19 11:29 UTC, mathetake commented on examples/foreign_call_on_tick/README.md
> +//TODO
Could you resolve?

2021-05-19 12:28 UTC, mathetake approved these changes
Thanks @zhenjunMa

2021-05-19 12:38 UTC, merged