Adds headers based on argument for "http_headers" example
tetratelabs/proxy-wasm-go-sdk pull request #339
Opened 2022-11-09 14:43 UTC by jonathanvila

In order to check on a basic `curl` command the execution of the wasm extension, the `http_headers` example now will add to the response a header based on the value of the argument and also a hardcoded header to check that is working even with an empty argument.

2022-11-09 17:05 UTC, mathetake commented
Need tests and comments on the added fields.

2022-11-09 18:06 UTC, jonathanvila commented
Added tests @mathetake as you suggested.

2022-11-09 20:05 UTC, mathetake requested changes
also you want to make a change in the test inside e2e/**

2022-11-09 20:05 UTC, mathetake commented on examples/http_headers/main.go
> +	headerValue string
needs comment

2022-11-09 20:05 UTC, mathetake commented on examples/http_headers/main.go
> +func (ctx *httpHeaders) OnHttpResponseHeaders(_ int, _ bool) types.Action {
please do not hide `numHeaders` and `endOfStream` as it's intentional to show users what's coming to the callbacks

2022-11-09 20:05 UTC, mathetake commented on examples/http_headers/main.go
> +func (p *pluginContext) OnPluginStart(_ int) types.OnPluginStartStatus {
same - plz revert the parameter name change

2022-11-09 20:05 UTC, mathetake commented on examples/http_headers/main.go
> +func (*vmContext) NewPluginContext(_ uint32) types.PluginContext {
same

2022-11-11 14:57 UTC, jonathanvila commented
@mathetake is the code ready to be merged now ?

2022-11-11 16:55 UTC, mathetake commented on examples/http_headers/main.go
> +	// Header passed by argument. If not empty will be added to the response
what is argument?

2022-11-11 16:57 UTC, mathetake commented on examples/http_headers/main.go
> +	// Header passed by argument. If not empty will be added to the response
```suggestion
```

2022-11-11 17:01 UTC, mathetake commented on examples/http_headers/README.md
> +In case there is information in the argument it will add the header to the response:
I don't believe the custom header is optional -- the plugin configuration fails if not present.

```suggestion
In envoy.yaml, the custom header is given as the plugin configuration like the following:

```yaml
                          configuration:
                            "@type": type.googleapis.com/google.protobuf.StringValue
                            value: |
                              {
                                "header": "x-wasm-header",
                                "value": "demo-wasm"
                              }
```

and this adds the `x-wasm-header: demo-wasm` header to all the responses.
```

2022-11-11 17:02 UTC, mathetake commented on examples/http_headers/README.md
> +```
```suggestion
```

2022-11-11 17:03 UTC, mathetake commented on examples/http_headers/README.md
> +
```yaml
                          configuration:
                            "@type": type.googleapis.com/google.protobuf.StringValue
                            value: |
                              {
                                "header": "x-wasm-header",
                                "value": "demo-wasm"
                              }
```

and this adds the `x-wasm-header: demo-wasm` header to all the responses.

2022-11-11 17:03 UTC, mathetake commented on examples/http_headers/README.md
> +
```suggestion
and this adds the `x-wasm-header: demo-wasm` header to all the responses.
```

2022-11-11 17:11 UTC, merged

2022-11-11 17:12 UTC, jonathanvila commented
Thanks a lot for your help @mathetake